server:
  port: 8010
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

logging:
  config: classpath:logback.xml
  level:
    cn.hd.amss.dao: debug

#数据库链接信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lcms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  application:
    name: AMSS-EUREKA-CLIENT

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.hd.amss.entity
  check-config-location: false