
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: false
    register-with-eureka: false

logging:
  level:
    root: info
server:
  port: 8761
  application:
    name: EUREKA-SERVER
